<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LaunchProfile>RealEstate</LaunchProfile>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AnalysisMode>AllEnabledByDefault</AnalysisMode>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<UserSecretsId>79778ee3-6d4a-4bf3-8e70-111a26831ddd</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
		<PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
