@RealEstate_HostAddress = https://localhost:5069


GET {{RealEstate_HostAddress}}/property/get-list
Authorization: bearer {{$bearerToken}}

###

GET {{RealEstate_HostAddress}}/property/get/{{propertyId}}
Authorization: bearer {{$bearerToken}}

###

POST {{RealEstate_HostAddress}}/property/add
Authorization: bearer {{$bearerToken}}
Content-Type: application/json

{
  //CreateDTO
}

###

PUT {{RealEstate_HostAddress}}/property/update/{{propertyId}}
Authorization: bearer {{$bearerToken}}
Content-Type: application/json

{
  //UpdateDTO
}

###

@propertyId=string
DELETE {{RealEstate_HostAddress}}/property/delete/{{propertyId}}
Authorization: bearer {{$bearerToken}}

###

DELETE {{RealEstate_HostAddress}}/property/delete-all
Authorization: bearer {{$bearerToken}}

###
